import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Link href={"csr"}>
        <a>CSR</a>
      </Link>
      <br />
      <br />
      <Link href={"ssr"}>
        <a>SSR</a>
      </Link>
      <br />
      <br />
      <Link href={"ssg"}>
        <a>SSG</a>
      </Link>
    </div>
  );
};

export default Home;
